# Generated by Django 3.0.5 on 2021-11-21 15:18

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields
import joboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='SOME STRING', max_length=70)),
                ('logo_url', models.CharField(default='SOME STRING', max_length=200)),
                ('title', models.CharField(default='SOME STRING', max_length=200)),
                ('location', models.CharField(default='SOME STRING', max_length=200)),
                ('skills', djongo.models.fields.ArrayField(default=[], model_container=joboard.models.Skill)),
                ('exp', djongo.models.fields.ArrayField(default=[], model_container=joboard.models.Experience)),
                ('exp_total', models.IntegerField(default=0)),
                ('exp_relevant_total', models.IntegerField(default=0)),
                ('exp_last_total', models.IntegerField(default=0)),
                ('educations', djongo.models.fields.ArrayField(default=[], model_container=joboard.models.Education)),
                ('contacts', djongo.models.fields.EmbeddedField(default='', model_container=joboard.models.Contact)),
                ('about', models.CharField(default='SOME STRING', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
