# Generated by Django 3.0.5 on 2021-11-19 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
